node {
    def app

    stage('Clone Repository') {
      /* Let's make sure we have the repository cloned to our workspace */
		  checkout scm
    }
	
    stage('Build Artifact') {
      dir('headend-service') {
        sh "mvn clean package"
      }
    }
	
    stage('Build Docker Image') {
      /* This builds the actual image; synonymous to
      * docker build on the command line */
      dir('headend-service') {
        app = docker.build("sherwinamihan/headend-service")
      }       
    }

    stage('Test Image') {
      /* Ideally, we would run a test framework against our image.
      * For this example, we're using a Volkswagen-type approach ;-) */
      dir('headend-service') {
        app.inside {
          sh 'echo "Tests passed"'
        }
      }
    }
	
    stage('Push Image') {
      /* Finally, we'll push the image with two tags:
      * First, the incremental build number from Jenkins
      * Second, the 'latest' tag.
      * Pushing multiple tags is cheap, as all the layers are reused. */
      dir('headend-service') {
        sh 'echo "Image pushed"'
      
        /*docker.withRegistry('https://index.docker.io/v1/', 'docker-hub-credentials') {
          app.push("${env.BUILD_NUMBER}")
          app.push("latest")
        }*/
      }
    }
	
    stage('Update Service') {
      dir('headend-service') {
        // sh 'docker ps -f name=headend-service -q | xargs --no-run-if-empty docker container stop'
        // sh 'docker container ls -a -fname=headend-service -q | xargs -r docker container rm'
        // def apiContainer = docker.image("sherwinamihan/headend-service").run("--name headend-service")

        sh 'echo updating headend-service'
        sh 'docker service update --image sherwinamihan/headend-service:latest prepaid_headend-service'
        sh 'echo headend-service is now running at http://172.18.13.12'
      }		
    }
}
